--- nie zapisały sie stare zad wiec odnowa...
SELECT nazwa_produktu, cena_sprzedazy FROM produkty WHERE cena_sprzedazy > 5000;x
SELECT nazwa_produktu, min_stan_magazynowy FROM produkty WHERE min_stan_magazynowy >= 10;
SELECT nazwa_produktu, cena_sprzedazy FROM produkty WHERE nazwa_produktu LIKE 'Samsung%';
SELECT imie, nazwisko, email FROM klienci WHERE email LIKE '%@gmail.com';
SELECT nazwa_produktu, cena_sprzedazy, opis FROM produkty WHERE nazwa_produktu LIKE '%Pro%';
SELECT nazwa_produktu, cena_sprzedazy FROM produkty WHERE cena_sprzedazy BETWEEN 1000 AND 3000;
SELECT nazwa_produktu, waga, jednostka_miary FROM produkty WHERE waga BETWEEN 0.1 AND 1;
SELECT nazwa_produktu, id_producenta FROM produkty WHERE id_producenta IN (1, 2, 11);
SELECT imie, nazwisko, stanowisko FROM pracownicy WHERE stanowisko IN ('Magazynier', 'Kierownik magazynu', 'Sprzedawca');
SELECT nazwa_produktu, cena_sprzedazy, dostepny FROM produkty WHERE dostepny = 1 AND cena_sprzedazy < 2000;
SELECT nazwa_produktu, dostepny, na_zamowienie FROM produkty WHERE dostepny = 0 OR na_zamowienie = 1;
SELECT nazwa_produktu, kod_produktu FROM produkty WHERE kod_produktu LIKE '%IP14%';
SELECT nazwa_produktu, id_kategorii FROM produkty WHERE id_kategorii NOT IN (14, 19, 20);
SELECT imie, nazwisko, grupa_klientow FROM klienci WHERE grupa_klientow <> 'Premium';
SELECT nazwa_produktu, cena_zakupu FROM produkty WHERE cena_zakupu NOT BETWEEN 500 AND 2000;
SELECT nazwa_produktu, cena_sprzedazy FROM produkty WHERE nazwa_produktu LIKE '%Laptop%' AND cena_sprzedazy BETWEEN 5000 AND 10000;
SELECT id_zamowienia, data_zamowienia, status_zamowienia FROM zamowienia WHERE status_zamowienia IN ('w realizacji', 'w przygotowaniu');
SELECT nazwa_produktu, kod_produktu FROM produkty WHERE kod_produktu LIKE 'APPL%' OR kod_produktu LIKE 'SAMS%';
SELECT nazwa_produktu, cena_zakupu, cena_sprzedazy FROM produkty WHERE cena_sprzedazy - cena_zakupu > 3000;
SELECT nazwa_produktu, cena_sprzedazy, id_kategorii FROM produkty WHERE (nazwa_produktu LIKE 'Samsung%' OR nazwa_produktu LIKE 'Sony%') AND cena_sprzedazy BETWEEN 1000 AND 6000 AND id_kategorii IN (19, 20, 24, 25, 26);
SELECT nazwa_produktu, id_producenta FROM produkty WHERE nazwa_produktu NOT LIKE '%Samsung%';
SELECT nazwa_produktu, waga, dostepny, na_zamowienie FROM produkty WHERE dostepny = 1 AND na_zamowienie = 0 AND waga < 1;
SELECT imie, nazwisko FROM pracownicy WHERE nazwisko >= 'K' AND nazwisko <= 'P';
SELECT id_stanu, id_produktu, id_magazynu, ilosc FROM stany_magazynowe WHERE id_produktu IN (1, 5, 10, 15, 20);
SELECT nazwa_produktu, id_producenta FROM produkty WHERE (nazwa_produktu LIKE '%iPhone%' OR nazwa_produktu LIKE '%Galaxy%') AND id_producenta IN (1, 2);
SELECT COUNT(*) AS liczba_produktow FROM produkty;
SELECT AVG(cena_sprzedazy) AS srednia_cena FROM produkty;
SELECT MAX(cena_sprzedazy) AS maksymalna_cena, MIN(cena_sprzedazy) AS minimalna_cena FROM produkty;
SELECT COUNT(*) AS liczba_produktow FROM produkty WHERE id_kategorii = 19;
SELECT SUM(ilosc) AS suma_ilosci FROM stany_magazynowe WHERE id_magazynu = 1;
SELECT id_kategorii, COUNT(*) AS liczba_produktow FROM produkty GROUP BY id_kategorii;
SELECT id_producenta, AVG(cena_sprzedazy) AS srednia_cena FROM produkty GROUP BY id_producenta;
SELECT id_kategorii, COUNT(*) AS liczba_produktow FROM produkty GROUP BY id_kategorii HAVING COUNT(*) > 3;
SELECT SUM(ilosc) AS suma_ilosci, AVG(ilosc) AS srednia_ilosc FROM stany_magazynowe WHERE id_magazynu = 1;
SELECT status_zamowienia, COUNT(*) AS liczba_zamowien FROM zamowienia GROUP BY status_zamowienia;
SELECT nazwa_produktu, data_wprowadzenia FROM produkty WHERE YEAR(data_wprowadzenia) = 2022;
SELECT nazwa_produktu, data_wprowadzenia FROM produkty WHERE data_wprowadzenia BETWEEN '2022-01-01' AND '2022-12-31';
SELECT imie, nazwisko, data_rejestracji FROM klienci WHERE data_rejestracji > '2021-01-01';
SELECT nazwa_produktu, DATEDIFF(CURDATE(), data_wprowadzenia) AS dni_od_wprowadzenia FROM produkty;
SELECT id_zamowienia, data_zamowienia FROM zamowienia WHERE MONTH(data_zamowienia) = 3 AND YEAR(data_zamowienia) = 2023;
SELECT imie, nazwisko, TIMESTAMPDIFF(YEAR, data_urodzenia, CURDATE()) AS wiek FROM pracownicy;
SELECT nazwa_produktu, YEAR(data_wprowadzenia) AS rok_wprowadzenia FROM produkty;
SELECT nazwa_producenta, TIMESTAMPDIFF(YEAR, data_wspolpracy_od, CURDATE()) AS lata_wspolpracy FROM producenci;
SELECT nazwa_produktu, cena_zakupu, cena_sprzedazy, (cena_sprzedazy - cena_zakupu) AS marza FROM produkty;
SELECT nazwa_produktu, cena_zakupu, cena_sprzedazy, ROUND((cena_sprzedazy - cena_zakupu) / cena_zakupu * 100, 2) AS procent_marzy FROM produkty;
SELECT nazwa_produktu, CEIL(cena_sprzedazy) AS cena_zaokraglona_gora FROM produkty;
SELECT nazwa_produktu, FLOOR(cena_sprzedazy) AS cena_zaokraglona_dol FROM produkty;
SELECT nazwa_produktu, ABS(cena_sprzedazy - 5000) AS roznica_bezwzgledna FROM produkty;
SELECT nazwa_produktu, waga, POWER(waga, 2) AS waga_kwadrat FROM produkty;
SELECT nazwa_produktu, ROUND(SQRT(cena_sprzedazy), 2) AS pierwiastek_ceny FROM produkty;
SELECT UPPER(nazwa_produktu) AS nazwa_wielkimi FROM produkty;
SELECT LOWER(imie) AS imie_male, LOWER(nazwisko) AS nazwisko_male FROM klienci;
SELECT nazwa_produktu, LENGTH(nazwa_produktu) AS dlugosc_nazwy FROM produkty;
SELECT imie, nazwisko, CONCAT(imie, ' ', nazwisko) AS pelne_imie_nazwisko FROM klienci;
SELECT nazwa_produktu, LEFT(opis, 20) AS skrocony_opis FROM produkty;
SELECT kod_produktu, RIGHT(kod_produktu, 3) AS ostatnie_znaki FROM produkty;
SELECT TRIM(nazwa_produktu) AS nazwa_bez_spacji FROM produkty;
SELECT nazwa_produktu, LOCATE('Pro', nazwa_produktu) AS pozycja_pro FROM produkty;
SELECT REPLACE(nazwa_produktu, 'Samsung', 'SAMSUNG ELECTRONICS') AS zmieniona_nazwa FROM produkty;
SELECT imie, SUBSTRING(imie, 1, 3) AS poczatek_imienia FROM klienci;
SELECT nazwa_produktu, ROUND(cena_sprzedazy * 0.23, 2) AS kwota_vat FROM produkty;
SELECT UPPER(nazwa_kategorii) AS nazwa_wielkimi, LENGTH(nazwa_kategorii) AS dlugosc_nazwy FROM kategorie_produktow;
SELECT imie, nazwisko, CONCAT(LOWER(imie), '.', LOWER(nazwisko), '@firma.pl') AS email_pracownika FROM pracownicy;
SELECT nazwa_produktu, ROUND(cena_sprzedazy / 1.23, 2) AS cena_netto FROM produkty;
SELECT COUNT(*) AS liczba_produktow FROM produkty WHERE cena_sprzedazy > (SELECT AVG(cena_sprzedazy) FROM produkty);
SELECT id_produktu, (cena_sprzedazy - (SELECT MIN(cena_sprzedazy) FROM produkty)) AS roznica_od_minimalnej FROM produkty;
SELECT nazwa_produktu, ROUND(cena_sprzedazy / cena_zakupu, 2) AS mnoznik FROM produkty;
SELECT imie, nazwisko, LEFT(imie, 1) AS pierwsza_litera FROM klienci;
SELECT nazwa_produktu, SUBSTRING_INDEX(nazwa_produktu, ' ', -1) AS ostatnie_slowo FROM produkty;
SELECT MONTH(data_zamowienia) AS miesiac, COUNT(*) AS liczba_zamowien FROM zamowienia WHERE YEAR(data_zamowienia) = 2023 GROUP BY MONTH(data_zamowienia);

